name: Fix dylib dependencies

on: [push, pull_request]

jobs:
  check-dylib:
    strategy:
      fail-fast: false
      matrix:
        # See https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: List dependencies (macOS)
        run: otool -L ./bin/openocd
      - name: Try to run unfixed openocd
        run: ./bin/openocd --version || true
      - name: Fix dylib dependencies
        run: |
          cd bin        
          # Fix openocd binary to use local dylibs
          echo "Fixing openocd dependencies..."
          install_name_tool -change /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib "@executable_path/./libusb-1.0.0.dylib" ./openocd
          install_name_tool -change /opt/homebrew/opt/hidapi/lib/libhidapi.0.dylib "@executable_path/./libhidapi.0.dylib" ./openocd
          
          # Verify the changes
          otool -L ./openocd
      - name: Try to run fixed openocd
        run: ./bin/openocd --version || true
      - name: Upload fixed openocd
        uses: actions/upload-artifact@v4
        with:
          name: openocd-fixed
          path: |
            bin/openocd
            bin/libusb-1.0.0.dylib
            bin/libhidapi.0.dylib
